In [1]:
import os
from pathlib import Path

import pandas as pd
import polars as pl

import matplotlib.pyplot as plt
import seaborn as sns

import scipy
import sklearn
import tensorflow as tf
import xgboost as xgb
import lightgbm as lgb
import catboost as cb

import mllabs

import sys
print(sys.version)

for i in [pd, pl, plt, sns, scipy, sklearn, tf, xgb, lgb, cb, mllabs]:
    if hasattr(i, '__version__'):
        print(i.__name__, i.__version__)
    else:
        print(i.__name__)

2026-03-06 01:20:00.850328: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-06 01:20:00.889589: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-03-06 01:20:01.942448: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
/home/sun9sun9/python312/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

3.12.12 (main, Dec 27 2025, 11:08:36) [GCC 13.3.0]
pandas 2.3.3
polars 1.38.1
matplotlib.pyplot
seaborn 0.13.2
scipy 1.16.3
sklearn 1.8.0
tensorflow 2.20.0
xgboost 3.2.0
lightgbm
catboost 1.2.8
mllabs 0.6.0

In [5]:
data_path = Path('data')

if not os.path.exists(data_path / 'train.csv'):
    !kaggle competitions download -c playground-series-s6e3
    !unzip playground-series-s6e3.zip -d data
    !rm playground-series-s6e3.zip

Downloading playground-series-s6e3.zip to /home/sun9sun9/work/ml-labs/examples/kaggle_s6e3
 87%|█████████████████████████████████     | 13.0M/14.9M [00:01<00:00, 17.8MB/s]
100%|██████████████████████████████████████| 14.9M/14.9M [00:01<00:00, 11.2MB/s]
Archive:  playground-series-s6e3.zip
  inflating: data/sample_submission.csv
  inflating: data/test.csv
  inflating: data/train.csv

In [17]:
from mllabs.processor import PolarsLoader, PandasConverter, ExprProcessor
from sklearn.pipeline import make_pipeline

loader = make_pipeline(
    PolarsLoader(predefined_types={'id': pl.Int64}),
    PandasConverter(index_col = 'id')
)
df_train = loader.fit_transform([data_path / 'train.csv']).assign(
    Churn = lambda x: (x['Churn'] == 'Yes').astype('int8')
)
df_test = loader.transform([data_path / 'test.csv'])

In [18]:
df_data_spec = loader[0].df_type_.join(
    pd.Series(loader[0].pl_type_, name = 'actual_dtype')
)
display(df_data_spec)
df_train.shape, df_test.shape

,min,max,na,count,n_unique,dtype,f32,i32,i16,i8,actual_dtype
feature,,,,,,,,,,,
Churn,NaN,NaN,0.0,594194.0,2.0,String,False,False,False,False,Categorical
Contract,NaN,NaN,0.0,594194.0,3.0,String,False,False,False,False,Categorical
Dependents,NaN,NaN,0.0,594194.0,2.0,String,False,False,False,False,Categorical
DeviceProtection,NaN,NaN,0.0,594194.0,3.0,String,False,False,False,False,Categorical
InternetService,NaN,NaN,0.0,594194.0,3.0,String,False,False,False,False,Categorical
MonthlyCharges,18.25,118.75,0.0,594194.0,1921.0,Float64,True,True,True,True,Float32
MultipleLines,NaN,NaN,0.0,594194.0,3.0,String,False,False,False,False,Categorical
OnlineBackup,NaN,NaN,0.0,594194.0,3.0,String,False,False,False,False,Categorical
OnlineSecurity,NaN,NaN,0.0,594194.0,3.0,String,False,False,False,False,Categorical
PaperlessBilling,NaN,NaN,0.0,594194.0,2.0,String,False,False,False,False,Categorical
Partner,NaN,NaN,0.0,594194.0,2.0,String,False,False,False,False,Categorical
PaymentMethod,NaN,NaN,0.0,594194.0,4.0,String,False,False,False,False,Categorical
PhoneService,NaN,NaN,0.0,594194.0,2.0,String,False,False,False,False,Categorical
SeniorCitizen,0.00,1.00,0.0,594194.0,2.0,Int64,True,True,True,True,Int8
StreamingMovies,NaN,NaN,0.0,594194.0,3.0,String,False,False,False,False,Categorical
StreamingTV,NaN,NaN,0.0,594194.0,3.0,String,False,False,False,False,Categorical
TechSupport,NaN,NaN,0.0,594194.0,3.0,String,False,False,False,False,Categorical
TotalCharges,18.80,8684.80,0.0,594194.0,31910.0,Float64,True,True,True,False,Float32
gender,NaN,NaN,0.0,594194.0,2.0,String,False,False,False,False,Categorical
id,0.00,594193.00,0.0,594194.0,594194.0,Int64,True,True,False,False,Int64
tenure,1.00,72.00,0.0,594194.0,72.0,Int64,True,True,True,True,Int8

((594194, 20), (254655, 19))

In [19]:
set(df_train.columns) - set(df_test.columns)

{'Churn'}

In [20]:
target = 'Churn'
X_all = df_test.columns.tolist()

In [21]:
df_train[target].value_counts()

Churn
0    460377
1    133817
Name: count, dtype: int64

In [26]:
df_data_spec.query("n_unique == 2.0")

,min,max,na,count,n_unique,dtype,f32,i32,i16,i8,actual_dtype
feature,,,,,,,,,,,
Churn,NaN,NaN,0.0,594194.0,2.0,String,False,False,False,False,Categorical
Dependents,NaN,NaN,0.0,594194.0,2.0,String,False,False,False,False,Categorical
PaperlessBilling,NaN,NaN,0.0,594194.0,2.0,String,False,False,False,False,Categorical
Partner,NaN,NaN,0.0,594194.0,2.0,String,False,False,False,False,Categorical
PhoneService,NaN,NaN,0.0,594194.0,2.0,String,False,False,False,False,Categorical
SeniorCitizen,0.0,1.0,0.0,594194.0,2.0,Int64,True,True,True,True,Int8
gender,NaN,NaN,0.0,594194.0,2.0,String,False,False,False,False,Categorical

In [37]:
df_train.loc[:, df_data_spec.query("n_unique == 2.0").index].apply(
    lambda x: x.unique().tolist(), axis = 0, result_type = 'reduce'
)

feature
Churn                       [0, 1]
Dependents               [Yes, No]
PaperlessBilling         [Yes, No]
Partner                  [Yes, No]
PhoneService             [Yes, No]
SeniorCitizen               [0, 1]
gender              [Male, Female]
dtype: object

In [34]:
pd.DataFrame.apply?

Signature:
pd.DataFrame.apply(
    self,
    func: 'AggFuncType',
    axis: 'Axis' = 0,
    raw: 'bool' = False,
    result_type: "Literal['expand', 'reduce', 'broadcast'] | None" = None,
    args=(),
    by_row: "Literal[False, 'compat']" = 'compat',
    engine: "Literal['python', 'numba']" = 'python',
    engine_kwargs: 'dict[str, bool] | None' = None,
    **kwargs,
)
Docstring:
Apply a function along an axis of the DataFrame.

Objects passed to the function are Series objects whose index is
either the DataFrame's index (``axis=0``) or the DataFrame's columns
(``axis=1``). By default (``result_type=None``), the final return type
is inferred from the return type of the applied function. Otherwise,
it depends on the `result_type` argument.

Parameters
----------
func : function
    Function to apply to each column or row.
axis : {0 or 'index', 1 or 'columns'}, default 0
    Axis along which the function is applied:

    * 0 or 'index': apply function to each column.
    * 1 or 'columns': apply function to each row.

raw : bool, default False
    Determines if row or column is passed as a Series or ndarray object:

    * ``False`` : passes each row or column as a Series to the
      function.
    * ``True`` : the passed function will receive ndarray objects
      instead.
      If you are just applying a NumPy reduction function this will
      achieve much better performance.

result_type : {'expand', 'reduce', 'broadcast', None}, default None
    These only act when ``axis=1`` (columns):

    * 'expand' : list-like results will be turned into columns.
    * 'reduce' : returns a Series if possible rather than expanding
      list-like results. This is the opposite of 'expand'.
    * 'broadcast' : results will be broadcast to the original shape
      of the DataFrame, the original index and columns will be
      retained.

    The default behaviour (None) depends on the return value of the
    applied function: list-like results will be returned as a Series
    of those. However if the apply function returns a Series these
    are expanded to columns.
args : tuple
    Positional arguments to pass to `func` in addition to the
    array/series.
by_row : False or "compat", default "compat"
    Only has an effect when ``func`` is a listlike or dictlike of funcs
    and the func isn't a string.
    If "compat", will if possible first translate the func into pandas
    methods (e.g. ``Series().apply(np.sum)`` will be translated to
    ``Series().sum()``). If that doesn't work, will try call to apply again with
    ``by_row=True`` and if that fails, will call apply again with
    ``by_row=False`` (backward compatible).
    If False, the funcs will be passed the whole Series at once.

    .. versionadded:: 2.1.0

engine : {'python', 'numba'}, default 'python'
    Choose between the python (default) engine or the numba engine in apply.

    The numba engine will attempt to JIT compile the passed function,
    which may result in speedups for large DataFrames.
    It also supports the following engine_kwargs :

    - nopython (compile the function in nopython mode)
    - nogil (release the GIL inside the JIT compiled function)
    - parallel (try to apply the function in parallel over the DataFrame)

      Note: Due to limitations within numba/how pandas interfaces with numba,
      you should only use this if raw=True

    Note: The numba compiler only supports a subset of
    valid Python/numpy operations.

    Please read more about the `supported python features
    <https://numba.pydata.org/numba-doc/dev/reference/pysupported.html>`_
    and `supported numpy features
    <https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html>`_
    in numba to learn what you can or cannot use in the passed function.

    .. versionadded:: 2.2.0

engine_kwargs : dict
    Pass keyword arguments to the engine.
    This is currently only used by the numba engine,
    see the documentation for the engine argument for more information.
**kwargs
    Additional keyword arguments to pass as keywords arguments to
    `func`.

Returns
-------
Series or DataFrame
    Result of applying ``func`` along the given axis of the
    DataFrame.

See Also
--------
DataFrame.map: For elementwise operations.
DataFrame.aggregate: Only perform aggregating type operations.
DataFrame.transform: Only perform transforming type operations.

Notes
-----
Functions that mutate the passed object can produce unexpected
behavior or errors and are not supported. See :ref:`gotchas.udf-mutation`
for more details.

Examples
--------
>>> df = pd.DataFrame([[4, 9]] * 3, columns=['A', 'B'])
>>> df
   A  B
0  4  9
1  4  9
2  4  9

Using a numpy universal function (in this case the same as
``np.sqrt(df)``):

>>> df.apply(np.sqrt)
     A    B
0  2.0  3.0
1  2.0  3.0
2  2.0  3.0

Using a reducing function on either axis

>>> df.apply(np.sum, axis=0)
A    12
B    27
dtype: int64

>>> df.apply(np.sum, axis=1)
0    13
1    13
2    13
dtype: int64

Returning a list-like will result in a Series

>>> df.apply(lambda x: [1, 2], axis=1)
0    [1, 2]
1    [1, 2]
2    [1, 2]
dtype: object

Passing ``result_type='expand'`` will expand list-like results
to columns of a Dataframe

>>> df.apply(lambda x: [1, 2], axis=1, result_type='expand')
   0  1
0  1  2
1  1  2
2  1  2

Returning a Series inside the function is similar to passing
``result_type='expand'``. The resulting column names
will be the Series index.

>>> df.apply(lambda x: pd.Series([1, 2], index=['foo', 'bar']), axis=1)
   foo  bar
0    1    2
1    1    2
2    1    2

Passing ``result_type='broadcast'`` will ensure the same shape
result, whether list-like or scalar is returned by the function,
and broadcast it along the axis. The resulting column names will
be the originals.

>>> df.apply(lambda x: [1, 2], axis=1, result_type='broadcast')
   A  B
0  1  2
1  1  2
2  1  2
File:      ~/python312/lib/python3.12/site-packages/pandas/core/frame.py
Type:      function